# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 04:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vrpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField()),
                ('source', models.CharField(max_length=30)),
                ('batch', models.CharField(max_length=30)),
                ('checked', models.BooleanField(default=False)),
                ('qualified', models.BooleanField(default=False)),
                ('vrpage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vrpages.VRPage')),
            ],
        ),
    ]
