# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vrpages', '0002_rawurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawurl',
            name='domain',
            field=models.CharField(default='', max_length=30),
        ),
    ]
