# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vrpages', '0004_polishurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polishurl',
            old_name='url',
            new_name='rawurl',
        ),
        migrations.AddField(
            model_name='polishurl',
            name='polished_url',
            field=models.URLField(default=''),
        ),
    ]
