# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vrpages', '0005_auto_20161123_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polishurl',
            name='polished_url',
            field=models.URLField(),
        ),
    ]
