# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vrpages', '0006_auto_20161123_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polishurl',
            name='broken_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='polishurl',
            name='contact_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
