# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 18:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vrpages', '0009_auto_20161128_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polishurl',
            name='polisher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='polishurls', to=settings.AUTH_USER_MODEL),
        ),
    ]
