# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vrpages', '0010_auto_20161129_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polishurl',
            name='polisher',
        ),
    ]
