# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 02:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vrpages', '0015_assignrawurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unsubscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('vrpage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vrpages.VRPage')),
            ],
        ),
    ]
